'use strict';
const $=s=>document.querySelector(s), app=$('#app');
let token=localStorage.getItem('uno50_token')||'', me=null, avatar=Number(localStorage.getItem('uno50_avatar')||1), ws=null, state=null, rooms=[];
const maps={pirate:'Barco pirata',egypt:'Egito antigo',rome:'Roma antiga',edo:'Japão Edo',silk:'Rota da Seda'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function page(html,footer=true){app.innerHTML=`<section class="screen">${html}</section>${footer?'<div class="footer">v1.2.0 V2026 · Feito por BomVelhinho Studios · Instagram</div>':''}`}
function panel(title,body){return `<div class="panel"><h1 class="brand">UNO50</h1><p class="subtitle">${title}</p>${body}</div>`}
function err(msg=''){return `<div id="error" class="error">${esc(msg)}</div>`}
async function api(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(token)h.Authorization=`Bearer ${token}`;const r=await fetch(path,{...opt,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`HTTP_${r.status}`);return d}
function terms(){page(panel('Termos de uso',`<div class="stack"><p class="small">Respeite outros jogadores. Exploração de falhas, automação abusiva e comportamento malicioso podem resultar em suspensão.</p><button class="primary" id="go">Continuar</button></div>`));$('#go').onclick=login}
function login(msg=''){page(panel('Entrar',`<div class="stack"><input id="user" class="field" autocomplete="username" placeholder="Usuário"><input id="pass" class="field" type="password" autocomplete="current-password" placeholder="Senha">${err(msg)}<button class="primary" id="enter">Entrar</button><button class="link" id="forgot">Esqueci minha senha</button><button class="link" id="register">Cadastrar</button></div>`));$('#enter').onclick=doLogin;$('#forgot').onclick=()=>$('#error').textContent='Recuperação de senha está indisponível.';$('#register').onclick=register}
function register(){page(panel('Cadastrar',`<div class="stack"><input id="user" class="field" autocomplete="username" placeholder="Usuário"><input id="email" class="field" autocomplete="email" placeholder="E-mail (opcional)"><input id="pass" class="field" type="password" autocomplete="new-password" placeholder="Senha (mínimo 8 caracteres)"><input id="pass2" class="field" type="password" autocomplete="new-password" placeholder="Confirmar senha">${err()}<button class="primary" id="save">Cadastrar</button><button class="link" id="back">Voltar</button></div>`));$('#save').onclick=doRegister;$('#back').onclick=login}
async function doLogin(){try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:$('#user').value,password:$('#pass').value})});token=d.token;localStorage.setItem('uno50_token',token);me=d.user;platform()}catch(e){$('#error').textContent='Não foi possível entrar. Verifique os dados.'}}
async function doRegister(){if($('#pass').value!==$('#pass2').value)return $('#error').textContent='As senhas não conferem.';try{const d=await api('/api/auth/register',{method:'POST',body:JSON.stringify({username:$('#user').value,email:$('#email').value,password:$('#pass').value})});token=d.token;localStorage.setItem('uno50_token',token);me=d.user;platform()}catch(e){$('#error').textContent=e.message==='USERNAME_OR_EMAIL_EXISTS'?'Usuário ou e-mail já cadastrado.':'Não foi possível cadastrar.'}}
function platform(){page(panel('Escolha sua plataforma atual',`<div class="stack"><button id="mobile">Celular</button><button id="desktop">Computador</button></div>`));$('#mobile').onclick=()=>savePlatform('mobile');$('#desktop').onclick=()=>savePlatform('desktop')}
async function savePlatform(p){try{const d=await api('/api/profile',{method:'PUT',body:JSON.stringify({platform:p})});me=d.user;home()}catch{home()}}
function home(){page(`<div class="panel center"><h1 class="brand">UNO50</h1><img class="avatar" src="/characters/${avatar}.svg" onerror="this.style.display='none'"><div class="menu"><button id="profile">Lápis</button><button id="play">Jogar</button><button id="rooms">Modo online / salas</button><button id="settings">Configuração</button><button class="danger" id="logout">Sair</button></div></div>`);$('#profile').onclick=profile;$('#play').onclick=solo;$('#rooms').onclick=roomMenu;$('#settings').onclick=settings;$('#logout').onclick=()=>{token='';me=null;localStorage.removeItem('uno50_token');login()}}
async function profile(){page(panel('Foto do personagem',`<img class="avatar" src="/characters/${avatar}.svg"><div class="avatar-grid">${Array.from({length:10},(_,i)=>`<button data-a="${i+1}"><img src="/characters/${i+1}.svg"></button>`).join('')}</div><div class="stack"><button id="back">Voltar</button></div>`));document.querySelectorAll('[data-a]').forEach(b=>b.onclick=async()=>{avatar=Number(b.dataset.a);localStorage.setItem('uno50_avatar',avatar);try{await api('/api/profile',{method:'PUT',body:JSON.stringify({avatarId:avatar})})}catch{}profile()});$('#back').onclick=home}
function settings(){page(panel('Configuração',`<div class="stack"><label class="small">Brilho</label><input id="bright" type="range" min="30" max="100" value="100"><button id="sound">Som: ligado</button><button id="anim">Animações: ligadas</button><button id="back">Voltar</button></div>`));let sound=true,anim=false;$('#sound').onclick=()=>{$('#sound').textContent=`Som: ${sound?'desligado':'ligado'}`;sound=!sound};$('#anim').onclick=()=>{$('#anim').textContent=`Animações: ${anim?'ligadas':'reduzidas'}`;anim=!anim};$('#back').onclick=home}
function solo(){gameLocal(2)}
function roomMenu(){page(panel('Modo online / salas',`<div class="stack"><button id="create">Criar sala</button><button id="public">Salas públicas</button><button id="join">Entrar em sala</button><button id="back">Voltar</button></div>`));$('#create').onclick=createRoom;$('#public').onclick=publicRooms;$('#join').onclick=()=>joinRoom();$('#back').onclick=home}
function createRoom(){page(panel('Criar sala',`<div class="stack"><input id="name" class="field" placeholder="Nome da sala (obrigatório)"><input id="password" class="field" type="password" placeholder="Senha opcional"><select id="vis" class="field"><option value="public">Pública</option><option value="private">Privada</option></select><select id="mode" class="field"><option>solo</option><option>duo</option><option>trio</option></select><label class="small"><input id="bots" type="checkbox"> Com bots</label><select id="map" class="field">${Object.entries(maps).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><input id="desc" class="field" placeholder="Descrição"><div id="error" class="error"></div><button class="primary" id="make">Criar</button><button id="back">Voltar</button></div>`));$('#make').onclick=async()=>{try{const d=await api('/api/rooms',{method:'POST',body:JSON.stringify({name:$('#name').value,password:$('#password').value,visibility:$('#vis').value,mode:$('#mode').value,bots:$('#bots').checked,mapId:$('#map').value,description:$('#desc').value})});if(d.matchId)connectMatch(d.matchId);else publicRooms()}catch(e){$('#error').textContent=e.message}};$('#back').onclick=roomMenu}
async function publicRooms(){try{const d=await api('/api/rooms');rooms=d.rooms||[]}catch(e){rooms=[]}page(panel('Salas públicas',`<div class="room-list">${rooms.length?rooms.map(r=>`<div class="room"><strong>${esc(r.name)}</strong><span class="small">${esc(maps[r.mapId]||r.mapId)} · ${esc(r.mode)} · ${r.players}/${r.maxPlayers}</span><br><button data-room="${esc(r.code)}">Entrar</button></div>`).join(''):'<p class="small">Nenhuma sala pública disponível.</p>'}</div><div class="stack" style="margin-top:12px"><button id="refresh">Atualizar</button><button id="back">Voltar</button></div>`));document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>joinRoom(b.dataset.room));$('#refresh').onclick=publicRooms;$('#back').onclick=roomMenu}
async function joinRoom(code){code=code||prompt('Código da sala');if(!code)return;const pass=prompt('Senha (deixe vazio se não houver)')||'';try{const d=await api(`/api/rooms/${encodeURIComponent(code)}/join`,{method:'POST',body:JSON.stringify({password:pass})});if(d.matchId)connectMatch(d.matchId);else publicRooms()}catch(e){roomMenu();setTimeout(()=>alert('Não foi possível entrar: '+e.message),0)}}
function connectMatch(id){if(ws)ws.close();const proto=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${proto}://${location.host}/?token=${encodeURIComponent(token)}`);ws.onopen=()=>ws.send(JSON.stringify({type:'join_match',matchId:id}));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='state'){state=m.data;renderOnline()}else if(m.type==='error')alert(m.error)};ws.onclose=()=>{ws=null}}
function send(type,payload={}){if(ws?.readyState===1)ws.send(JSON.stringify({type,nonce:crypto.randomUUID(),...payload}))}
function renderOnline(){const s=state;if(!s)return;const top=s.topCard||{color:'wild',type:'number',value:'?'};const label=top.type==='number'?top.value:top.type.toUpperCase();page(`<div class="game"><img class="map" src="/maps/${s.mapId==='ancient_egypt'?'egypt':s.mapId==='pirate_ship'?'pirate':s.mapId==='ancient_rome'?'rome':s.mapId==='edo_japan'?'edo':'silk'}.svg"><div class="table"></div><div class="discard ${top.color}">${esc(label)}</div><div class="topbar"><span>UNO50 · ${esc(maps[s.mapId]||s.mapId)}</span><button class="danger" id="leave">Sair</button></div><div class="game-actions"><button id="draw">Comprar</button></div><div class="hand">${(s.hand||[]).map((c,i)=>`<button class="card ${c.color}" data-card="${i}">${c.type==='number'?c.value:c.type}</button>`).join('')}</div></div>`,false);document.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.card);const c=s.hand[i];if(c.type==='wild'||c.type==='wild4'){const color=prompt('Cor: red, yellow, green ou blue','red');send('play',{cardIndex:i,chosenColor:color})}else send('play',{cardIndex:i})});$('#draw').onclick=()=>send('draw');$('#leave').onclick=()=>{if(ws)ws.close();home()}}
function gameLocal(n){let deck=[];const colors=['red','yellow','green','blue'];for(const c of colors){deck.push({color:c,type:'number',value:0});for(let i=1;i<=9;i++){deck.push({color:c,type:'number',value:i},{color:c,type:'number',value:i})}}for(let i=0;i<4;i++)deck.push({color:'wild',type:'wild'},{color:'wild',type:'wild4'});deck.sort(()=>Math.random()-.5);let hand=deck.splice(0,7),top=deck.pop();function render(){page(`<div class="game"><div class="table"></div><div class="discard ${top.color}">${top.type==='number'?top.value:top.type}</div><div class="topbar"><span>UNO50 · Solo</span><button class="danger" id="leave">Sair</button></div><div class="game-actions"><button id="draw">Comprar</button></div><div class="hand">${hand.map((c,i)=>`<button class="card ${c.color}" data-c="${i}">${c.type==='number'?c.value:c.type}</button>`).join('')}</div></div>`,false);document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.c),c=hand[i];if(c.type==='wild'||c.color===top.color||c.value===top.value){top=hand.splice(i,1)[0];if(!hand.length){alert('Você venceu!');home();return}render()}});$('#draw').onclick=()=>{if(deck.length)hand.push(deck.pop());render()};$('#leave').onclick=home}render()}
async function boot(){if(token){try{const d=await api('/api/me');me=d.user;home();return}catch{token='';localStorage.removeItem('uno50_token')}}terms()}
boot();
