using Godot;
using System;
using System.Collections.Generic;

namespace Uno50;

public partial class Uno50App : Node2D
{
    enum Screen { Terms, Login, Register, Platform, Home, Profile, Settings, Rooms, CreateRoom, Game }
    Screen screen=Screen.Terms; Control root=new(); UnoGame? game; int avatar=1; string platform="mobile"; MapInfo selectedMap=MapCatalog.All[0];
    readonly Color bg=new("#080a10"); readonly Color panel=new("#111722"); readonly Color text=new("#f5f2e8"); readonly Color muted=new("#9ba4b3");
    public override void _Ready(){ AddChild(root); root.SetAnchorsAndOffsetsPreset(Control.LayoutPreset.FullRect); ShowTerms(); }
    void Clear(){foreach(Node n in root.GetChildren()) n.QueueFree();}
    Label L(string s,int size=20){var l=new Label{Text=s,HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};l.AddThemeFontSizeOverride("font_size",size);l.AddThemeColorOverride("font_color",text);return l;}
    Button B(string s,Action action){var b=new Button{Text=s,CustomMinimumSize=new Vector2(260,52)};b.AddThemeFontSizeOverride("font_size",20);b.Pressed+=action;return b;}
    VBoxContainer Box(){var v=new VBoxContainer{Alignment=BoxContainer.AlignmentMode.Center};v.AddThemeConstantOverride("separation",12);v.SetAnchorsAndOffsetsPreset(Control.LayoutPreset.Center);v.CustomMinimumSize=new Vector2(420,500);return v;}
    void Base(string title){Clear();var bgc=new ColorRect{Color=bg};bgc.SetAnchorsAndOffsetsPreset(Control.LayoutPreset.FullRect);root.AddChild(bgc);var titleL=L(title,48);titleL.Position=new Vector2(0,34);titleL.Size=new Vector2(1280,70);root.AddChild(titleL);Decor(root);}
    void Decor(Node parent){for(int i=0;i<12;i++){var c=new ColorRect{Color=new Color(0.15f+(i%4)*.1f,.05f,.07f,.16f),Size=new Vector2(44,70),Position=new Vector2((i*113)%1250,-90+i*71)};c.Rotation=(i%2==0?.25f:-.2f);parent.AddChild(c);var tw=CreateTween();tw.SetLoops();tw.TweenProperty(c,"position:y",760.0,2.8+i*.12).SetTrans(Tween.TransitionType.Linear);tw.TweenProperty(c,"position:y",-100.0,0.01);}}
    void CenterAdd(Control box,Control child){box.AddChild(child);}
    void ShowTerms(){Base("UNO50");var v=Box();root.AddChild(v);v.AddChild(L("Termos de uso",28));v.AddChild(L("Use o jogo com respeito. Trapaça, abuso e exploração de falhas podem levar à suspensão.\n\nAo continuar, você aceita as regras do Uno50.",17));v.AddChild(B("CONTINUAR",ShowLogin));}
    void ShowLogin(){Base("UNO50");var v=Box();root.AddChild(v);v.AddChild(L("LOGIN",28));var u=new LineEdit{PlaceholderText="Usuário ou e-mail",CustomMinimumSize=new Vector2(360,50)};var p=new LineEdit{PlaceholderText="Senha",Secret=true,CustomMinimumSize=new Vector2(360,50)};v.AddChild(u);v.AddChild(p);v.AddChild(B("ENTRAR",()=>{if(string.IsNullOrWhiteSpace(u.Text)||string.IsNullOrWhiteSpace(p.Text))return;ShowPlatform();}));v.AddChild(B("ESQUECI MINHA SENHA",()=>Toast("Recuperação de senha indisponível no momento.")));v.AddChild(B("CRIAR UMA CONTA",ShowRegister));}
    void ShowRegister(){Base("UNO50");var v=Box();root.AddChild(v);v.AddChild(L("CADASTRAR",28));var u=new LineEdit{PlaceholderText="Usuário ou e-mail"};var p=new LineEdit{PlaceholderText="Senha",Secret=true};var p2=new LineEdit{PlaceholderText="Confirmar senha",Secret=true};v.AddChild(u);v.AddChild(p);v.AddChild(p2);v.AddChild(B("CADASTRAR",()=>ShowPlatform()));v.AddChild(B("VOLTAR",ShowLogin));}
    void ShowPlatform(){Base("UNO50");var v=Box();root.AddChild(v);v.AddChild(L("ESCOLHA SUA PLATAFORMA",26));v.AddChild(B("CELULAR",()=>{platform="mobile";ShowHome();}));v.AddChild(B("COMPUTADOR",()=>{platform="desktop";ShowHome();}));}
    void ShowHome(){Base("UNO50");var v=Box();root.AddChild(v);var img=new TextureRect{CustomMinimumSize=new Vector2(120,120),ExpandMode=TextureRect.ExpandModeEnum.IgnoreSize,StretchMode=TextureRect.StretchModeEnum.KeepAspectCentered};img.Texture=Load<Texture2D>($"res://Assets/Characters/character_{avatar}.svg");v.AddChild(img);v.AddChild(B("✎",ShowProfile));v.AddChild(B("JOGAR",ShowPlayModes));v.AddChild(B("MODO ONLINE / SALAS",ShowRooms));var cfg=B("CONFIGURAÇÃO",ShowSettings);v.AddChild(cfg);v.AddChild(B("SAIR",ShowLogin));v.AddChild(L("v1.2.0 V2026\nFeito por BomVelhinho Studios\nInstagram",13));}
    void ShowProfile(){Base("PERSONAGEM");var v=Box();root.AddChild(v);v.AddChild(L("ESCOLHA SUA FOTO",25));var grid=new GridContainer{Columns=5};for(int i=1;i<=10;i++){int x=i;var b=new TextureButton{TextureNormal=Load<Texture2D>($"res://Assets/Characters/character_{i}.svg"),CustomMinimumSize=new Vector2(72,72),IgnoreTextureSize=true};b.Pressed+=()=>{avatar=x;ShowProfile();};grid.AddChild(b);}v.AddChild(grid);v.AddChild(B("VOLTAR",ShowHome));}
    void ShowSettings(){Base("CONFIGURAÇÃO");var v=Box();root.AddChild(v);v.AddChild(L("Arquivos: 78%",18));v.AddChild(L("Ping: 42 ms",18));var bright=new HSlider{MinValue=30,MaxValue=100,Value=100,CustomMinimumSize=new Vector2(360,30)};v.AddChild(L("Brilho",16));v.AddChild(bright);Button sound; sound=B("SOM: LIGADO",()=>sound.Text=sound.Text.Contains("LIGADO")?"SOM: DESLIGADO":"SOM: LIGADO");v.AddChild(sound);Button anim; anim=B("ANIMAÇÕES: LIGADAS",()=>anim.Text=anim.Text.Contains("LIGADAS")?"ANIMAÇÕES: REDUZIDAS":"ANIMAÇÕES: LIGADAS");v.AddChild(anim);v.AddChild(B("VOLTAR",ShowHome));}
    void ShowPlayModes(){Base("JOGAR");var v=Box();root.AddChild(v);v.AddChild(B("SOLO",()=>StartGame(2,true)));v.AddChild(B("DUO",()=>StartGame(2,false)));v.AddChild(B("TRIO",()=>StartGame(3,false)));v.AddChild(B("VOLTAR",ShowHome));}
    void ShowRooms(){Base("MODO ONLINE / SALAS");var v=Box();root.AddChild(v);v.AddChild(B("CRIAR SALA",ShowCreateRoom));v.AddChild(B("SALAS PÚBLICAS",()=>Toast("Lista pública preparada para o servidor online.")));v.AddChild(B("ENTRAR EM SALA",()=>Toast("Digite o código e a senha na próxima etapa.")));v.AddChild(B("VOLTAR",ShowHome));}
    void ShowCreateRoom(){Base("CRIAR SALA");var v=Box();root.AddChild(v);v.AddChild(L("Nome da sala é obrigatório",16));var name=new LineEdit{PlaceholderText="Nome da sala"};var pass=new LineEdit{PlaceholderText="Senha opcional",Secret=true};var desc=new LineEdit{PlaceholderText="Descrição"};v.AddChild(name);v.AddChild(pass);Button vis; vis=B("PÚBLICA",()=>vis.Text=vis.Text=="PÚBLICA"?"PRIVADA":"PÚBLICA");v.AddChild(vis);Button mode; mode=B("MODO: SOLO",()=>mode.Text=mode.Text switch{"MODO: SOLO"=>"MODO: DUO","MODO: DUO"=>"MODO: TRIO",_=>"MODO: SOLO"});v.AddChild(mode);var bots=B("BOTS: COM BOTS",()=>bots.Text=bots.Text.Contains("COM")?"BOTS: SEM BOTS":"BOTS: COM BOTS");v.AddChild(bots);v.AddChild(L("Mapa",16));var map=B(selectedMap.Name,()=>{selectedMap=MapCatalog.All[(Array.IndexOf(MapCatalog.All,selectedMap)+1)%MapCatalog.All.Length];ShowCreateRoom();});v.AddChild(map);v.AddChild(desc);v.AddChild(B("CRIAR",()=>Toast(string.IsNullOrWhiteSpace(name.Text)?"Nome da sala é obrigatório.":"Sala criada: "+name.Text)));v.AddChild(B("VOLTAR",ShowRooms));}
    void StartGame(int count,bool bots){screen=Screen.Game;Base("UNO50");game=new UnoGame();game.Start(count,bots);DrawGame();}
    void DrawGame(){Clear();var bgc=new ColorRect{Color=new Color(selectedMap.Accent)};bgc.SetAnchorsAndOffsetsPreset(Control.LayoutPreset.FullRect);root.AddChild(bgc);var mapTex=new TextureRect{Texture=Load<Texture2D>($"res://Assets/Maps/{selectedMap.Id}.svg"),ExpandMode=TextureRect.ExpandModeEnum.IgnoreSize,StretchMode=TextureRect.StretchModeEnum.KeepAspectCovered};mapTex.SetAnchorsAndOffsetsPreset(Control.LayoutPreset.FullRect);mapTex.Modulate=new Color(1,1,1,.72f);root.AddChild(mapTex);Decor(root);var top=L(game!.Players[game.CurrentPlayer].Name+"  •  "+Math.Ceiling(game.TurnRemaining)+"s",22);top.Position=new Vector2(0,18);top.Size=new Vector2(1280,60);root.AddChild(top);var info=L(selectedMap.Name,18);info.Position=new Vector2(0,70);info.Size=new Vector2(1280,40);root.AddChild(info);var center=L("BARALHO        "+game.Discard[^1].Label+"\n\nMESA UNO50",38);center.Position=new Vector2(300,170);center.Size=new Vector2(680,280);center.AddThemeColorOverride("font_color",text);root.AddChild(center);var hand=new HBoxContainer{Position=new Vector2(280,530),Size=new Vector2(720,120),Alignment=BoxContainer.AlignmentMode.Center};foreach(var c in game.Players[0].Hand){var b=B(c.Label,()=>{int idx=game.Players[0].Hand.IndexOf(c);if(game.Play(0,idx,c.IsWild?CardColor.Red:c.Color,Guid.NewGuid().ToString("N")))DrawGame();});b.Modulate=c.UiColor;hand.AddChild(b);}root.AddChild(hand);var uno=B("UNO!",()=>{game.Players[0].UnoCalled=true;Toast("UNO registrado.");});uno.Position=new Vector2(40,500);root.AddChild(uno);var draw=B("COMPRAR",()=>{game.DrawForCurrent(Guid.NewGuid().ToString("N"));DrawGame();});draw.Position=new Vector2(40,560);root.AddChild(draw);root.AddChild(B("SAIR",ShowHome));if(game.Finished)Toast("Vencedor: "+game.Winner);}
    double botDelay=0;
    public override void _Process(double delta){
        if(game==null||game.Finished)return;
        game.Tick(delta);
        botDelay-=delta;
        if(game.Players[game.CurrentPlayer].IsBot && botDelay<=0){
            var bot=game.Players[game.CurrentPlayer]; int idx=-1;
            for(int i=0;i<bot.Hand.Count;i++){if(GameRules.CanPlay(bot.Hand[i],game.Discard[^1],game.ActiveColor,bot.Hand)){idx=i;break;}}
            if(idx>=0) game.Play(game.CurrentPlayer,idx,bot.Hand[idx].IsWild?CardColor.Red:bot.Hand[idx].Color,Guid.NewGuid().ToString("N"));
            else game.DrawForCurrent(Guid.NewGuid().ToString("N"));
            botDelay=0.8; DrawGame();
        }
    }
    void Toast(string msg){var p=new Panel{Position=new Vector2(330,620),Size=new Vector2(620,70)};var l=L(msg,17);l.SetAnchorsAndOffsetsPreset(Control.LayoutPreset.FullRect);p.AddChild(l);root.AddChild(p);var tw=CreateTween();tw.TweenInterval(2);tw.TweenCallback(Callable.From(()=>p.QueueFree()));}
}
